## 두번째 창 UI
from PyQt5 import QtCore, QtGui, QtWidgets
## 다음윈도우 불러오기
from newwindow1 import Ui_newwindow11

class Ui_NewWindow1(object):
    ## 새창열기 함수 버튼뒤에 clicked = lambda:self.openwindow()
    def openwindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_newwindow11()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, NewWindow1):
        NewWindow1.setObjectName("NewWindow1")
        NewWindow1.resize(546, 840)
        self.centralwidget = QtWidgets.QWidget(NewWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 531, 831))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        # 챕터 1 
        self.chapter1f = QtWidgets.QPushButton(self.page, clicked = lambda:self.openwindow())
        self.chapter1f.setGeometry(QtCore.QRect(70, 710, 411, 111))
        self.chapter1f.setObjectName("chapter1f")
        self.chapter1c = QtWidgets.QPushButton(self.page, clicked = lambda:self.openwindow())
        self.chapter1c.setGeometry(QtCore.QRect(70, 320, 411, 111))
        self.chapter1c.setObjectName("chapter1c")
        self.label1 = QtWidgets.QLabel(self.page)
        self.label1.setGeometry(QtCore.QRect(220, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.chapter1d = QtWidgets.QPushButton(self.page, clicked = lambda:self.openwindow())
        self.chapter1d.setGeometry(QtCore.QRect(70, 450, 411, 111))
        self.chapter1d.setObjectName("chapter1d")
        self.chapter1a = QtWidgets.QPushButton(self.page, clicked = lambda:self.openwindow())
        self.chapter1a.setGeometry(QtCore.QRect(70, 60, 411, 111))
        self.chapter1a.setObjectName("chapter1a")
        self.chapter1e = QtWidgets.QPushButton(self.page, clicked = lambda:self.openwindow())
        self.chapter1e.setGeometry(QtCore.QRect(70, 580, 411, 111))
        self.chapter1e.setObjectName("chapter1e")
        self.chapter1b = QtWidgets.QPushButton(self.page, clicked = lambda:self.openwindow())
        self.chapter1b.setGeometry(QtCore.QRect(70, 190, 411, 111))
        self.chapter1b.setObjectName("chapter1b")
        self.stackedWidget.addWidget(self.page)
        ## 챕터 2
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.chapter2f = QtWidgets.QPushButton(self.page_2, clicked = lambda:self.openwindow())
        self.chapter2f.setGeometry(QtCore.QRect(60, 710, 411, 111))
        self.chapter2f.setObjectName("chapter2f")
        self.chapter2c = QtWidgets.QPushButton(self.page_2, clicked = lambda:self.openwindow())
        self.chapter2c.setGeometry(QtCore.QRect(60, 320, 411, 111))
        self.chapter2c.setObjectName("chapter2c")
        self.label2 = QtWidgets.QLabel(self.page_2)
        self.label2.setGeometry(QtCore.QRect(210, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.chapter2d = QtWidgets.QPushButton(self.page_2, clicked = lambda:self.openwindow())
        self.chapter2d.setGeometry(QtCore.QRect(60, 450, 411, 111))
        self.chapter2d.setObjectName("chapter2d")
        self.chapter2a = QtWidgets.QPushButton(self.page_2, clicked = lambda:self.openwindow())
        self.chapter2a.setGeometry(QtCore.QRect(60, 60, 411, 111))
        self.chapter2a.setObjectName("chapter2a")
        self.chapter2e = QtWidgets.QPushButton(self.page_2, clicked = lambda:self.openwindow())
        self.chapter2e.setGeometry(QtCore.QRect(60, 580, 411, 111))
        self.chapter2e.setObjectName("chapter2e")
        self.chapter2b = QtWidgets.QPushButton(self.page_2, clicked = lambda:self.openwindow())
        self.chapter2b.setGeometry(QtCore.QRect(60, 190, 411, 111))
        self.chapter2b.setObjectName("chapter2b")
        self.stackedWidget.addWidget(self.page_2)
        ## 챕터 3
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.chapter3f = QtWidgets.QPushButton(self.page_3, clicked = lambda:self.openwindow())
        self.chapter3f.setGeometry(QtCore.QRect(60, 710, 411, 111))
        self.chapter3f.setObjectName("chapter3f")
        self.label3 = QtWidgets.QLabel(self.page_3)
        self.label3.setGeometry(QtCore.QRect(210, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.chapter3c = QtWidgets.QPushButton(self.page_3, clicked = lambda:self.openwindow())
        self.chapter3c.setGeometry(QtCore.QRect(60, 320, 411, 111))
        self.chapter3c.setObjectName("chapter3c")
        self.chapter3d = QtWidgets.QPushButton(self.page_3, clicked = lambda:self.openwindow())
        self.chapter3d.setGeometry(QtCore.QRect(60, 450, 411, 111))
        self.chapter3d.setObjectName("chapter3d")
        self.chapter3b = QtWidgets.QPushButton(self.page_3, clicked = lambda:self.openwindow())
        self.chapter3b.setGeometry(QtCore.QRect(60, 190, 411, 111))
        self.chapter3b.setObjectName("chapter3b")
        self.chapter3a = QtWidgets.QPushButton(self.page_3, clicked = lambda:self.openwindow())
        self.chapter3a.setGeometry(QtCore.QRect(60, 60, 411, 111))
        self.chapter3a.setObjectName("chapter3a")
        self.chapter3e = QtWidgets.QPushButton(self.page_3, clicked = lambda:self.openwindow())
        self.chapter3e.setGeometry(QtCore.QRect(60, 580, 411, 111))
        self.chapter3e.setObjectName("chapter3e")
        self.stackedWidget.addWidget(self.page_3)
        # 챕터 4
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.chapter4f = QtWidgets.QPushButton(self.page_4, clicked = lambda:self.openwindow())
        self.chapter4f.setGeometry(QtCore.QRect(70, 720, 411, 111))
        self.chapter4f.setObjectName("chapter4f")
        self.label4 = QtWidgets.QLabel(self.page_4)
        self.label4.setGeometry(QtCore.QRect(220, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.chapter4c = QtWidgets.QPushButton(self.page_4, clicked = lambda:self.openwindow())
        self.chapter4c.setGeometry(QtCore.QRect(70, 330, 411, 111))
        self.chapter4c.setObjectName("chapter4c")
        self.chapter4d = QtWidgets.QPushButton(self.page_4, clicked = lambda:self.openwindow())
        self.chapter4d.setGeometry(QtCore.QRect(70, 460, 411, 111))
        self.chapter4d.setObjectName("chapter4d")
        self.chapter4b = QtWidgets.QPushButton(self.page_4, clicked = lambda:self.openwindow())
        self.chapter4b.setGeometry(QtCore.QRect(70, 200, 411, 111))
        self.chapter4b.setObjectName("chapter4b")
        self.chapter4a = QtWidgets.QPushButton(self.page_4, clicked = lambda:self.openwindow())
        self.chapter4a.setGeometry(QtCore.QRect(70, 70, 411, 111))
        self.chapter4a.setObjectName("chapter4a")
        self.chapter4e = QtWidgets.QPushButton(self.page_4, clicked = lambda:self.openwindow())
        self.chapter4e.setGeometry(QtCore.QRect(70, 590, 411, 111))
        self.chapter4e.setObjectName("chapter4e")
        self.stackedWidget.addWidget(self.page_4)
        # 챕터 5
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.chapter5f = QtWidgets.QPushButton(self.page_5, clicked = lambda:self.openwindow())
        self.chapter5f.setGeometry(QtCore.QRect(70, 710, 411, 111))
        self.chapter5f.setObjectName("chapter5f")
        self.label5 = QtWidgets.QLabel(self.page_5)
        self.label5.setGeometry(QtCore.QRect(220, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.chapter5c = QtWidgets.QPushButton(self.page_5, clicked = lambda:self.openwindow())
        self.chapter5c.setGeometry(QtCore.QRect(70, 320, 411, 111))
        self.chapter5c.setObjectName("chapter5c")
        self.chapter5d = QtWidgets.QPushButton(self.page_5, clicked = lambda:self.openwindow())
        self.chapter5d.setGeometry(QtCore.QRect(70, 450, 411, 111))
        self.chapter5d.setObjectName("chapter5d")
        self.chapter5b = QtWidgets.QPushButton(self.page_5, clicked = lambda:self.openwindow())
        self.chapter5b.setGeometry(QtCore.QRect(70, 190, 411, 111))
        self.chapter5b.setObjectName("chapter5b")
        self.chapter5a = QtWidgets.QPushButton(self.page_5, clicked = lambda:self.openwindow())
        self.chapter5a.setGeometry(QtCore.QRect(70, 60, 411, 111))
        self.chapter5a.setObjectName("chapter5a")
        self.chapter5e = QtWidgets.QPushButton(self.page_5, clicked = lambda:self.openwindow())
        self.chapter5e.setGeometry(QtCore.QRect(70, 580, 411, 111))
        self.chapter5e.setObjectName("chapter5e")
        self.stackedWidget.addWidget(self.page_5)
        # 챕터 6
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.chapter6f = QtWidgets.QPushButton(self.page_6, clicked = lambda:self.openwindow())
        self.chapter6f.setGeometry(QtCore.QRect(60, 710, 411, 111))
        self.chapter6f.setObjectName("chapter6f")
        self.label6 = QtWidgets.QLabel(self.page_6)
        self.label6.setGeometry(QtCore.QRect(210, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.chapter6c = QtWidgets.QPushButton(self.page_6, clicked = lambda:self.openwindow())
        self.chapter6c.setGeometry(QtCore.QRect(60, 320, 411, 111))
        self.chapter6c.setObjectName("chapter6c")
        self.chapter6d = QtWidgets.QPushButton(self.page_6, clicked = lambda:self.openwindow())
        self.chapter6d.setGeometry(QtCore.QRect(60, 450, 411, 111))
        self.chapter6d.setObjectName("chapter6d")
        self.chapter6b = QtWidgets.QPushButton(self.page_6, clicked = lambda:self.openwindow())
        self.chapter6b.setGeometry(QtCore.QRect(60, 190, 411, 111))
        self.chapter6b.setObjectName("chapter6b")
        self.chapter6a = QtWidgets.QPushButton(self.page_6, clicked = lambda:self.openwindow())
        self.chapter6a.setGeometry(QtCore.QRect(60, 60, 411, 111))
        self.chapter6a.setObjectName("chapter6a")
        self.chapter6e = QtWidgets.QPushButton(self.page_6, clicked = lambda:self.openwindow())
        self.chapter6e.setGeometry(QtCore.QRect(60, 580, 411, 111))
        self.chapter6e.setObjectName("chapter6e")
        self.stackedWidget.addWidget(self.page_6)
        # 챕터 7
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.chapter7e = QtWidgets.QPushButton(self.page_7, clicked = lambda:self.openwindow())
        self.chapter7e.setGeometry(QtCore.QRect(70, 580, 411, 111))
        self.chapter7e.setObjectName("chapter7e")
        self.chapter7b = QtWidgets.QPushButton(self.page_7, clicked = lambda:self.openwindow())
        self.chapter7b.setGeometry(QtCore.QRect(70, 190, 411, 111))
        self.chapter7b.setObjectName("chapter7b")
        self.chapter7c = QtWidgets.QPushButton(self.page_7, clicked = lambda:self.openwindow())
        self.chapter7c.setGeometry(QtCore.QRect(70, 320, 411, 111))
        self.chapter7c.setObjectName("chapter7c")
        self.chapter7a = QtWidgets.QPushButton(self.page_7, clicked = lambda:self.openwindow())
        self.chapter7a.setGeometry(QtCore.QRect(70, 60, 411, 111))
        self.chapter7a.setObjectName("chapter7a")
        self.label7 = QtWidgets.QLabel(self.page_7)
        self.label7.setGeometry(QtCore.QRect(220, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.chapter7d = QtWidgets.QPushButton(self.page_7, clicked = lambda:self.openwindow())
        self.chapter7d.setGeometry(QtCore.QRect(70, 450, 411, 111))
        self.chapter7d.setObjectName("chapter7d")
        self.chapter7f = QtWidgets.QPushButton(self.page_7, clicked = lambda:self.openwindow())
        self.chapter7f.setGeometry(QtCore.QRect(70, 710, 411, 111))
        self.chapter7f.setObjectName("chapter7f")
        self.stackedWidget.addWidget(self.page_7)
        # 챕터 8
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.chapter8e = QtWidgets.QPushButton(self.page_8, clicked = lambda:self.openwindow())
        self.chapter8e.setGeometry(QtCore.QRect(60, 580, 411, 111))
        self.chapter8e.setObjectName("chapter8e")
        self.label8 = QtWidgets.QLabel(self.page_8)
        self.label8.setGeometry(QtCore.QRect(210, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.chapter8b = QtWidgets.QPushButton(self.page_8, clicked = lambda:self.openwindow())
        self.chapter8b.setGeometry(QtCore.QRect(60, 190, 411, 111))
        self.chapter8b.setObjectName("chapter8b")
        self.chapter8d = QtWidgets.QPushButton(self.page_8, clicked = lambda:self.openwindow())
        self.chapter8d.setGeometry(QtCore.QRect(60, 450, 411, 111))
        self.chapter8d.setObjectName("chapter8d")
        self.chapter8c = QtWidgets.QPushButton(self.page_8, clicked = lambda:self.openwindow())
        self.chapter8c.setGeometry(QtCore.QRect(60, 320, 411, 111))
        self.chapter8c.setObjectName("chapter8c")
        self.chapter8a = QtWidgets.QPushButton(self.page_8, clicked = lambda:self.openwindow())
        self.chapter8a.setGeometry(QtCore.QRect(60, 60, 411, 111))
        self.chapter8a.setObjectName("chapter8a")
        self.chapter8f = QtWidgets.QPushButton(self.page_8, clicked = lambda:self.openwindow())
        self.chapter8f.setGeometry(QtCore.QRect(60, 710, 411, 111))
        self.chapter8f.setObjectName("chapter8f")
        self.stackedWidget.addWidget(self.page_8)
        # 챕터 9
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.chapter9f = QtWidgets.QPushButton(self.page_9, clicked = lambda:self.openwindow())
        self.chapter9f.setGeometry(QtCore.QRect(60, 710, 411, 111))
        self.chapter9f.setObjectName("chapter9f")
        self.label9 = QtWidgets.QLabel(self.page_9)
        self.label9.setGeometry(QtCore.QRect(210, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.chapter9c = QtWidgets.QPushButton(self.page_9, clicked = lambda:self.openwindow())
        self.chapter9c.setGeometry(QtCore.QRect(60, 320, 411, 111))
        self.chapter9c.setObjectName("chapter9c")
        self.chapter9d = QtWidgets.QPushButton(self.page_9, clicked = lambda:self.openwindow())
        self.chapter9d.setGeometry(QtCore.QRect(60, 450, 411, 111))
        self.chapter9d.setObjectName("chapter9d")
        self.chapter9b = QtWidgets.QPushButton(self.page_9, clicked = lambda:self.openwindow())
        self.chapter9b.setGeometry(QtCore.QRect(60, 190, 411, 111))
        self.chapter9b.setObjectName("chapter9b")
        self.chapter9a = QtWidgets.QPushButton(self.page_9, clicked = lambda:self.openwindow())
        self.chapter9a.setGeometry(QtCore.QRect(60, 60, 411, 111))
        self.chapter9a.setObjectName("chapter9a")
        self.chapter9e = QtWidgets.QPushButton(self.page_9, clicked = lambda:self.openwindow())
        self.chapter9e.setGeometry(QtCore.QRect(60, 580, 411, 111))
        self.chapter9e.setObjectName("chapter9e")
        self.stackedWidget.addWidget(self.page_9)
        NewWindow1.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewWindow1)
        self.stackedWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(NewWindow1)

    def retranslateUi(self, NewWindow1):
        _translate = QtCore.QCoreApplication.translate
        NewWindow1.setWindowTitle(_translate("NewWindow1", "MainWindow"))
        self.chapter1f.setText(_translate("NewWindow1", "PushButton"))
        self.chapter1c.setText(_translate("NewWindow1", "PushButton"))
        self.label1.setText(_translate("NewWindow1", "chapter1"))
        self.chapter1d.setText(_translate("NewWindow1", "PushButton"))
        self.chapter1a.setText(_translate("NewWindow1", "PushButton"))
        self.chapter1e.setText(_translate("NewWindow1", "PushButton"))
        self.chapter1b.setText(_translate("NewWindow1", "PushButton"))
        self.chapter2f.setText(_translate("NewWindow1", "chapter2"))
        self.chapter2c.setText(_translate("NewWindow1", "chapter2"))
        self.label2.setText(_translate("NewWindow1", "chapter2"))
        self.chapter2d.setText(_translate("NewWindow1", "chapter2"))
        self.chapter2a.setText(_translate("NewWindow1", "chapter2"))
        self.chapter2e.setText(_translate("NewWindow1", "chapter2"))
        self.chapter2b.setText(_translate("NewWindow1", "chapter2"))
        self.chapter3f.setText(_translate("NewWindow1", "PushButton"))
        self.label3.setText(_translate("NewWindow1", "chapter3"))
        self.chapter3c.setText(_translate("NewWindow1", "PushButton"))
        self.chapter3d.setText(_translate("NewWindow1", "PushButton"))
        self.chapter3b.setText(_translate("NewWindow1", "PushButton"))
        self.chapter3a.setText(_translate("NewWindow1", "PushButton"))
        self.chapter3e.setText(_translate("NewWindow1", "PushButton"))
        self.chapter4f.setText(_translate("NewWindow1", "chapter4"))
        self.label4.setText(_translate("NewWindow1", "chapter4"))
        self.chapter4c.setText(_translate("NewWindow1", "chapter4"))
        self.chapter4d.setText(_translate("NewWindow1", "chapter4"))
        self.chapter4b.setText(_translate("NewWindow1", "chapter4"))
        self.chapter4a.setText(_translate("NewWindow1", "chapter4"))
        self.chapter4e.setText(_translate("NewWindow1", "chapter4"))
        self.chapter5f.setText(_translate("NewWindow1", "chapter5"))
        self.label5.setText(_translate("NewWindow1", "chapter5"))
        self.chapter5c.setText(_translate("NewWindow1", "chapter5"))
        self.chapter5d.setText(_translate("NewWindow1", "chapter5"))
        self.chapter5b.setText(_translate("NewWindow1", "chapter5"))
        self.chapter5a.setText(_translate("NewWindow1", "chapter5"))
        self.chapter5e.setText(_translate("NewWindow1", "chapter5"))
        self.chapter6f.setText(_translate("NewWindow1", "chapter6"))
        self.label6.setText(_translate("NewWindow1", "chapter6"))
        self.chapter6c.setText(_translate("NewWindow1", "chapter6"))
        self.chapter6d.setText(_translate("NewWindow1", "chapter6"))
        self.chapter6b.setText(_translate("NewWindow1", "chapter6"))
        self.chapter6a.setText(_translate("NewWindow1", "chapter6"))
        self.chapter6e.setText(_translate("NewWindow1", "chapter6"))
        self.chapter7e.setText(_translate("NewWindow1", "chapter7"))
        self.chapter7b.setText(_translate("NewWindow1", "chapter7"))
        self.chapter7c.setText(_translate("NewWindow1", "chapter7"))
        self.chapter7a.setText(_translate("NewWindow1", "chapter7"))
        self.label7.setText(_translate("NewWindow1", "chapter7"))
        self.chapter7d.setText(_translate("NewWindow1", "chapter7"))
        self.chapter7f.setText(_translate("NewWindow1", "chapter7"))
        self.chapter8e.setText(_translate("NewWindow1", "chapter8"))
        self.label8.setText(_translate("NewWindow1", "chapter8"))
        self.chapter8b.setText(_translate("NewWindow1", "chapter8"))
        self.chapter8d.setText(_translate("NewWindow1", "chapter8"))
        self.chapter8c.setText(_translate("NewWindow1", "chapter8"))
        self.chapter8a.setText(_translate("NewWindow1", "chapter8"))
        self.chapter8f.setText(_translate("NewWindow1", "chapter8"))
        self.chapter9f.setText(_translate("NewWindow1", "chapter9"))
        self.label9.setText(_translate("NewWindow1", "chapter9"))
        self.chapter9c.setText(_translate("NewWindow1", "chapter9"))
        self.chapter9d.setText(_translate("NewWindow1", "chapter9"))
        self.chapter9b.setText(_translate("NewWindow1", "chapter9"))
        self.chapter9a.setText(_translate("NewWindow1", "chapter9"))
        self.chapter9e.setText(_translate("NewWindow1", "chapter9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewWindow1 = QtWidgets.QMainWindow()
    ui = Ui_NewWindow1()
    ui.setupUi(NewWindow1)
    NewWindow1.show()
    sys.exit(app.exec_())
